<?php
/**.
 * Implements hook_views_pre_render()
 */
function lilac_views_pre_render(\Drupal\views\ViewExecutable $view) {
  $view->element['#attached']['library'][] = 'lilac/';
}

/**
* Implements hook_preprocess_page(&$variables)
*/
function theme_name_preprocess_page(&$variables) {
  if (\Drupal::service('path.matcher')->isFrontPage() == 1) {
    $variables['#attached']['library'][] = 'theme_name/slick';
  }
}
